
name: 3proxy

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:

  build_3proxy:

    runs-on: windows-latest

    steps:
    - name: compile 3proxy (x64) with Visual C++
      run: |
        git clone --depth 1 -b master --single-branch https://github.com/3proxy/3proxy.git .
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        SET "PATH=C:\Program Files\OpenSSL\bin;%PATH%"
        SET "INCLUDE=C:\Program Files\OpenSSL\include;%INCLUDE%"
        SET "LIB=C:\Program Files\OpenSSL\lib;%LIB%"
        REM SET "LIB=C:\Program Files\OpenSSL\lib\VC;%LIB%"
        SET "LIB=C:\Program Files\OpenSSL\lib\VC\static;%LIB%"
        openssl version
        NMAKE /F Makefile.msvc64
      shell: CMD

    - uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}

