name: build-lftp

on:
  workflow_dispatch:

jobs:
  build-lftp:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Initialization environment and make
        run: |
          mkdir -p /opt/rh/
          yum install epel-release -y
          yum install wget unzip autoconf libtool gettext-devel automake gnulib readline-devel zlib-devel -y
          yum install centos-release-scl -y
          yum install devtoolset-11-gcc* -y
          scl enable devtoolset-11 bash
          mkdir /workdir
          cd /workdir
          wget https://github.com/tabraham/lftp/archive/refs/heads/master.zip
          unzip master.zip
          cd lftp-master
          ./autogen.sh
          make

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: lftp
          path: /workdir/lftp-master
