name: sealos

env:
  # Common versions
  GO_VERSION: "1.20"

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    
    steps:
    
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu \
            libbtrfs-dev libgpgme-dev libdevmapper-dev \
            qemu-user-static binfmt-support

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Clone
        run: |
          git clone --depth 1 -b master --single-branch https://github.com/labring/sealos.git .

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --clean --release-footer-tmpl=scripts/release/footer.md.tmpl --release-header-tmpl=scripts/release/head.md.tmpl
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/dist

