name: testapp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Clone source code
        run: |
          git clone --depth 1 --single-branch --branch dev-v2-rtsp https://github.com/tresvecesseis/ExoPlayer.git boxdir
          #wget https://github.com/takagen99/Box/raw/main/gradlew -O boxdir/demos/main/gradlew

      - name: Build with Gradle
        run: |
          cd boxdir
          chmod +x gradlew
          ./gradlew projects
          ./gradlew demos:assemblerelease --build-cache --parallel --daemon --stacktrace --warning-mode all

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rstptest
          path: boxdir
